### ISSUE TITLE
styles.css page

### ISSUE THREAD

**Issue by naassi** [naassi/taxi-log#1]
I am trying to add padding to the buttons to give them some space but I don't think the styles.css page is add correctly, might be the way I am rendering it, I know this is probably a really simple fix but the idea of this project is to get experience so thought best see.

**Comment by jgodson** [comment]
I assume it is different than what you have committed so far as there is no link in your html to styles.css or styles.css file up yet. You do it similar to how you added bootstrap, but href should be something like "../css/styles.css" or "/css/styles.css" if you don't want to have relative links.

**Comment by naassi** [comment]
Really i thought this was up to date i'll update it now, I have been trying to do it like you have said but its not working at all

**Comment by jgodson** [comment]
Ah, yes. Sorry. The way you are serving files, it will not work. You will have to include it in your response. Better way would probably be to change it so it just serves static files from a public directory instead of sending pieces of them.

**Comment by jgodson** [comment]
If you wanted to keep it the way you have it... You could probably have 2 header files. End the first one after title and rename it header 2. Open <style> tag in that one then res.write(fs.ReadFileSync('./css/styles/css'));

Then in file header2 close style and head tag and open body tag. I don't think this is a great way to do it, but for a learning experience it might work.

**Comment by naassi** [comment]
Thanks I am just trying to do it without using express to get practice with node then when I understand it better start using other libraries, what is the reason for 2 headers? would it not work in one ?

**Comment by naassi** [comment]
res.write('<style>' + fs.readFileSync('./css/styles.css') + '</style>');

This worked thanks, but there must be a smoother way of doing this without express?
